/********************************************************************
* libDiffAnalysis_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error libDiffAnalysis_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablelibDiffAnalysis_Dict();
extern void G__cpp_setup_inheritancelibDiffAnalysis_Dict();
extern void G__cpp_setup_typetablelibDiffAnalysis_Dict();
extern void G__cpp_setup_memvarlibDiffAnalysis_Dict();
extern void G__cpp_setup_globallibDiffAnalysis_Dict();
extern void G__cpp_setup_memfunclibDiffAnalysis_Dict();
extern void G__cpp_setup_funclibDiffAnalysis_Dict();
extern void G__set_cpp_environmentlibDiffAnalysis_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "./AnFmsPhotonAngDist.h"
#include "./AnDstQA.h"
#include "./AnEEmcRpCorr.h"
#include "./AnDiffJetCreateBinnedHist.h"
#include "./AnFmsRpCorrPpb.h"
#include "./AnFmsHotChFinder.h"
#include "./AnEEmcRpCorrMergedFullPpb.h"
#include "./AnRunEEmcRpTreeMakerPart1.h"
#include "./AnIncPion.h"
#include "./AnCalculateAN.h"
#include "./DiffJetXFnPhotonsANCalc.h"
#include "./AnFmsPos2ChLookupTable.h"
#include "./TAnFmsRpTreeReader.h"
#include "./DiffJetRawANCalc.h"
#include "./AnFmsRpCorrMergedFull.h"
#include "./AnRunDiffJetTreeMaker.h"
#include "./AnFmsRpQA.h"
#include "./DiffJetNum.h"
#include "./DiffJetAnaTreeQa.h"
#include "./AnFmsRpPionSource.h"
#include "./DiffJetRpSimQa.h"
#include "./AnRunNanoDstMaker.h"
#include "./AnFmsRpCorrUpb.h"
#include "./AnEEmcRpCorrUpb.h"
#include "./TAnEEmcRpTreeReader.h"
#include "./DiffJetXFANCalc.h"
#include "./DiffJetRpCheck.h"
#include "./AnFmsPhotonAngDistJobs.h"
#include "./AnRunFmsRpTreeMaker.h"
#include "./DiffJetXFNphotonsCalc.h"
#include "./DiffJetRpTreeCut.h"
#include "./AnRunAnTreeMaker.h"
#include "./DiffJetXFCalc.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__libDiffAnalysis_DictLN_TClass;
extern G__linked_taginfo G__libDiffAnalysis_DictLN_TBuffer;
extern G__linked_taginfo G__libDiffAnalysis_DictLN_TMemberInspector;
extern G__linked_taginfo G__libDiffAnalysis_DictLN_TString;
extern G__linked_taginfo G__libDiffAnalysis_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__libDiffAnalysis_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__libDiffAnalysis_DictLN_TClonesArray;
extern G__linked_taginfo G__libDiffAnalysis_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__libDiffAnalysis_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__libDiffAnalysis_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__libDiffAnalysis_DictLN_TTree;
extern G__linked_taginfo G__libDiffAnalysis_DictLN_TBranch;
extern G__linked_taginfo G__libDiffAnalysis_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__libDiffAnalysis_DictLN_TChain;
extern G__linked_taginfo G__libDiffAnalysis_DictLN_TAnFmsRpTreeReader;
extern G__linked_taginfo G__libDiffAnalysis_DictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__libDiffAnalysis_DictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__libDiffAnalysis_DictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__libDiffAnalysis_DictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__libDiffAnalysis_DictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__libDiffAnalysis_DictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__libDiffAnalysis_DictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__libDiffAnalysis_DictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__libDiffAnalysis_DictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__libDiffAnalysis_DictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__libDiffAnalysis_DictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__libDiffAnalysis_DictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__libDiffAnalysis_DictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__libDiffAnalysis_DictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__libDiffAnalysis_DictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__libDiffAnalysis_DictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__libDiffAnalysis_DictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__libDiffAnalysis_DictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__libDiffAnalysis_DictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__libDiffAnalysis_DictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__libDiffAnalysis_DictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__libDiffAnalysis_DictLN_TAnEEmcRpTreeReader;

/* STUB derived class for protected member access */
