/********************************************************************
* libEmJetAnalysis_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error libEmJetAnalysis_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablelibEmJetAnalysis_Dict();
extern void G__cpp_setup_inheritancelibEmJetAnalysis_Dict();
extern void G__cpp_setup_typetablelibEmJetAnalysis_Dict();
extern void G__cpp_setup_memvarlibEmJetAnalysis_Dict();
extern void G__cpp_setup_globallibEmJetAnalysis_Dict();
extern void G__cpp_setup_memfunclibEmJetAnalysis_Dict();
extern void G__cpp_setup_funclibEmJetAnalysis_Dict();
extern void G__set_cpp_environmentlibEmJetAnalysis_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "./EjReadAnalysisTree.h"
#include "./EjCalculateBeamAsymmetry.h"
#include "./EjSimpleAnalysisTreeQa.h"
#include "./EjRunEmJetTreeMakerEEmcSmd.h"
#include "./EjPlotAn.h"
#include "./EjCalculateANextended.h"
#include "./EjRunEmJetTreeMaker.h"
#include "./EjCreateBinnedHist.h"
#include "./EjMakeAnalysisTree.h"
#include "./EjJetQaPlots.h"
#include "./EjCreateBinnedHistZn.h"
#include "./EjCalculateAN.h"
#include "./EjCalculateANdirectMethod.h"
#include "./EjAna.h"
#include "./EjAnalysisTreeQa.h"
#include "./EjANprojection.h"
#include "./EjCalculateFalseAN.h"
#include "./EjCreateBinnedHistExtended.h"
#include "./EjCreateSimpleBinnedHist.h"
#include "./EjMakeSimpleAnalysisTree.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__libEmJetAnalysis_DictLN_TClass;
extern G__linked_taginfo G__libEmJetAnalysis_DictLN_TBuffer;
extern G__linked_taginfo G__libEmJetAnalysis_DictLN_TMemberInspector;
extern G__linked_taginfo G__libEmJetAnalysis_DictLN_TString;
extern G__linked_taginfo G__libEmJetAnalysis_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__libEmJetAnalysis_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__libEmJetAnalysis_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__libEmJetAnalysis_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__libEmJetAnalysis_DictLN_EjAna;

/* STUB derived class for protected member access */
