//
// File generated by rootcint at Wed Jun  9 11:39:00 2021

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME libEmJetAnalysis_Dict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "libEmJetAnalysis_Dict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void EjAna_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_EjAna(void *p = 0);
   static void *newArray_EjAna(Long_t size, void *p);
   static void delete_EjAna(void *p);
   static void deleteArray_EjAna(void *p);
   static void destruct_EjAna(void *p);
   static void streamer_EjAna(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::EjAna*)
   {
      ::EjAna *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::EjAna >(0);
      static ::ROOT::TGenericClassInfo 
         instance("EjAna", ::EjAna::Class_Version(), "././EjAna.h", 13,
                  typeid(::EjAna), ::ROOT::DefineBehavior(ptr, ptr),
                  &::EjAna::Dictionary, isa_proxy, 0,
                  sizeof(::EjAna) );
      instance.SetNew(&new_EjAna);
      instance.SetNewArray(&newArray_EjAna);
      instance.SetDelete(&delete_EjAna);
      instance.SetDeleteArray(&deleteArray_EjAna);
      instance.SetDestructor(&destruct_EjAna);
      instance.SetStreamerFunc(&streamer_EjAna);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::EjAna*)
   {
      return GenerateInitInstanceLocal((::EjAna*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::EjAna*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

//______________________________________________________________________________
atomic_TClass_ptr EjAna::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *EjAna::Class_Name()
{
   return "EjAna";
}

//______________________________________________________________________________
const char *EjAna::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::EjAna*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int EjAna::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::EjAna*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void EjAna::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::EjAna*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *EjAna::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::EjAna*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void EjAna::Streamer(TBuffer &R__b)
{
   // Stream an object of class EjAna.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      R__b.CheckByteCount(R__s, R__c, EjAna::IsA());
   } else {
      R__c = R__b.WriteVersion(EjAna::IsA(), kTRUE);
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void EjAna::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class EjAna.
      TClass *R__cl = ::EjAna::IsA();
      if (R__cl || R__insp.IsA()) { }
}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_EjAna(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::EjAna : new ::EjAna;
   }
   static void *newArray_EjAna(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::EjAna[nElements] : new ::EjAna[nElements];
   }
   // Wrapper around operator delete
   static void delete_EjAna(void *p) {
      delete ((::EjAna*)p);
   }
   static void deleteArray_EjAna(void *p) {
      delete [] ((::EjAna*)p);
   }
   static void destruct_EjAna(void *p) {
      typedef ::EjAna current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_EjAna(TBuffer &buf, void *obj) {
      ((::EjAna*)obj)->::EjAna::Streamer(buf);
   }
} // end of namespace ROOTDict for class ::EjAna

/********************************************************
* libEmJetAnalysis_Dict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtablelibEmJetAnalysis_Dict();

extern "C" void G__set_cpp_environmentlibEmJetAnalysis_Dict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("./EjReadAnalysisTree.h");
  G__add_compiledheader("./EjCalculateBeamAsymmetry.h");
  G__add_compiledheader("./EjSimpleAnalysisTreeQa.h");
  G__add_compiledheader("./EjRunEmJetTreeMakerEEmcSmd.h");
  G__add_compiledheader("./EjPlotAn.h");
  G__add_compiledheader("./EjCalculateANextended.h");
  G__add_compiledheader("./EjRunEmJetTreeMaker.h");
  G__add_compiledheader("./EjCreateBinnedHist.h");
  G__add_compiledheader("./EjMakeAnalysisTree.h");
  G__add_compiledheader("./EjJetQaPlots.h");
  G__add_compiledheader("./EjCreateBinnedHistZn.h");
  G__add_compiledheader("./EjCalculateAN.h");
  G__add_compiledheader("./EjCalculateANdirectMethod.h");
  G__add_compiledheader("./EjAna.h");
  G__add_compiledheader("./EjAnalysisTreeQa.h");
  G__add_compiledheader("./EjANprojection.h");
  G__add_compiledheader("./EjCalculateFalseAN.h");
  G__add_compiledheader("./EjCreateBinnedHistExtended.h");
  G__add_compiledheader("./EjCreateSimpleBinnedHist.h");
  G__add_compiledheader("./EjMakeSimpleAnalysisTree.h");
  G__cpp_reset_tagtablelibEmJetAnalysis_Dict();
}
#include <new>
extern "C" int G__cpp_dllrevlibEmJetAnalysis_Dict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* EjAna */
static int G__libEmJetAnalysis_Dict_184_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   EjAna* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new EjAna[n];
     } else {
       p = new((void*) gvp) EjAna[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new EjAna;
     } else {
       p = new((void*) gvp) EjAna;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__libEmJetAnalysis_DictLN_EjAna));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libEmJetAnalysis_Dict_184_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      EjAna::Print();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libEmJetAnalysis_Dict_184_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) EjAna::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libEmJetAnalysis_Dict_184_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) EjAna::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libEmJetAnalysis_Dict_184_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) EjAna::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libEmJetAnalysis_Dict_184_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      EjAna::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libEmJetAnalysis_Dict_184_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const EjAna*) G__getstructoffset())->IsA());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libEmJetAnalysis_Dict_184_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EjAna*) G__getstructoffset())->ShowMembers(*(TMemberInspector*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libEmJetAnalysis_Dict_184_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EjAna*) G__getstructoffset())->Streamer(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libEmJetAnalysis_Dict_184_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EjAna*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libEmJetAnalysis_Dict_184_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) EjAna::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libEmJetAnalysis_Dict_184_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) EjAna::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libEmJetAnalysis_Dict_184_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) EjAna::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libEmJetAnalysis_Dict_184_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) EjAna::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__libEmJetAnalysis_Dict_184_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   EjAna* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new EjAna(*(EjAna*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__libEmJetAnalysis_DictLN_EjAna));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef EjAna G__TEjAna;
static int G__libEmJetAnalysis_Dict_184_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (EjAna*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((EjAna*) (soff+(sizeof(EjAna)*i)))->~G__TEjAna();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (EjAna*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((EjAna*) (soff))->~G__TEjAna();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__libEmJetAnalysis_Dict_184_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   EjAna* dest = (EjAna*) G__getstructoffset();
   *dest = *(EjAna*) libp->para[0].ref;
   const EjAna& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */
static int G__libEmJetAnalysis_Dict__0_2180(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      EjReadAnalysisTree();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libEmJetAnalysis_Dict__0_2287(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 3:
      EjCalculateBeamAsymmetry(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])));
      G__setnull(result7);
      break;
   case 2:
      EjCalculateBeamAsymmetry(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1])));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libEmJetAnalysis_Dict__0_2288(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      EjSimpleAnalysisTreeQa(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1])));
      G__setnull(result7);
      break;
   case 1:
      EjSimpleAnalysisTreeQa(*((TString*) G__int(libp->para[0])));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libEmJetAnalysis_Dict__0_2289(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 4:
      EjRunEmJetTreeMakerEEmcSmd(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])), (Bool_t) G__int(libp->para[3]));
      G__setnull(result7);
      break;
   case 3:
      EjRunEmJetTreeMakerEEmcSmd(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])));
      G__setnull(result7);
      break;
   case 2:
      EjRunEmJetTreeMakerEEmcSmd(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1])));
      G__setnull(result7);
      break;
   case 1:
      EjRunEmJetTreeMakerEEmcSmd(*((TString*) G__int(libp->para[0])));
      G__setnull(result7);
      break;
   case 0:
      EjRunEmJetTreeMakerEEmcSmd();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libEmJetAnalysis_Dict__0_2290(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      EjPlotAn();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libEmJetAnalysis_Dict__0_2291(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 3:
      EjCalculateANextended(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])));
      G__setnull(result7);
      break;
   case 2:
      EjCalculateANextended(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1])));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libEmJetAnalysis_Dict__0_2292(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 4:
      EjRunEmJetTreeMaker(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])), (Bool_t) G__int(libp->para[3]));
      G__setnull(result7);
      break;
   case 3:
      EjRunEmJetTreeMaker(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])));
      G__setnull(result7);
      break;
   case 2:
      EjRunEmJetTreeMaker(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1])));
      G__setnull(result7);
      break;
   case 1:
      EjRunEmJetTreeMaker(*((TString*) G__int(libp->para[0])));
      G__setnull(result7);
      break;
   case 0:
      EjRunEmJetTreeMaker();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libEmJetAnalysis_Dict__0_2293(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 5:
      EjCreateBinnedHist((Int_t) G__int(libp->para[0]), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])), (Int_t) G__int(libp->para[3])
, (Int_t) G__int(libp->para[4]));
      G__setnull(result7);
      break;
   case 4:
      EjCreateBinnedHist((Int_t) G__int(libp->para[0]), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])), (Int_t) G__int(libp->para[3]));
      G__setnull(result7);
      break;
   case 3:
      EjCreateBinnedHist((Int_t) G__int(libp->para[0]), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libEmJetAnalysis_Dict__0_2294(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      EjMakeAnalysisTree(*((TString*) G__int(libp->para[0])), (Int_t) G__int(libp->para[1])
, *((TString*) G__int(libp->para[2])), *((TString*) G__int(libp->para[3]))
, *((TString*) G__int(libp->para[4])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libEmJetAnalysis_Dict__0_2295(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      EjJetQaPlots((Int_t) G__int(libp->para[0]), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])), *((TString*) G__int(libp->para[3])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libEmJetAnalysis_Dict__0_2296(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      EjCreateBinnedHistZn(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, (Int_t) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libEmJetAnalysis_Dict__0_2297(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 3:
      EjCalculateAN(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])));
      G__setnull(result7);
      break;
   case 2:
      EjCalculateAN(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1])));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libEmJetAnalysis_Dict__0_2298(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 3:
      EjCalculateANdirectMethod(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])));
      G__setnull(result7);
      break;
   case 2:
      EjCalculateANdirectMethod(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1])));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libEmJetAnalysis_Dict__0_2299(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 3:
      EjAnalysisTreeQa(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])));
      G__setnull(result7);
      break;
   case 2:
      EjAnalysisTreeQa(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1])));
      G__setnull(result7);
      break;
   case 1:
      EjAnalysisTreeQa(*((TString*) G__int(libp->para[0])));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libEmJetAnalysis_Dict__0_2300(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 3:
      EjANprojection(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])));
      G__setnull(result7);
      break;
   case 2:
      EjANprojection(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1])));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libEmJetAnalysis_Dict__0_2301(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 3:
      EjCalculateFalseAN(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])));
      G__setnull(result7);
      break;
   case 2:
      EjCalculateFalseAN(*((TString*) G__int(libp->para[0])), *((TString*) G__int(libp->para[1])));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libEmJetAnalysis_Dict__0_2302(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 6:
      EjCreateBinnedHistExtended((Int_t) G__int(libp->para[0]), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])), (Int_t) G__int(libp->para[3])
, (Int_t) G__int(libp->para[4]), (Int_t) G__int(libp->para[5]));
      G__setnull(result7);
      break;
   case 5:
      EjCreateBinnedHistExtended((Int_t) G__int(libp->para[0]), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])), (Int_t) G__int(libp->para[3])
, (Int_t) G__int(libp->para[4]));
      G__setnull(result7);
      break;
   case 4:
      EjCreateBinnedHistExtended((Int_t) G__int(libp->para[0]), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])), (Int_t) G__int(libp->para[3]));
      G__setnull(result7);
      break;
   case 3:
      EjCreateBinnedHistExtended((Int_t) G__int(libp->para[0]), *((TString*) G__int(libp->para[1]))
, *((TString*) G__int(libp->para[2])));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libEmJetAnalysis_Dict__0_2305(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      EjCreateSimpleBinnedHist((Int_t) G__int(libp->para[0]), *((TString*) G__int(libp->para[1])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__libEmJetAnalysis_Dict__0_2306(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      EjMakeSimpleAnalysisTree(*((TString*) G__int(libp->para[0])), (Int_t) G__int(libp->para[1])
, *((TString*) G__int(libp->para[2])), *((TString*) G__int(libp->para[3]))
, *((TString*) G__int(libp->para[4])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/*********************************************************
* Member function Stub
*********************************************************/

/* EjAna */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfunclibEmJetAnalysis_Dict {
 public:
  G__Sizep2memfunclibEmJetAnalysis_Dict(): p(&G__Sizep2memfunclibEmJetAnalysis_Dict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfunclibEmJetAnalysis_Dict::*p)();
};

size_t G__get_sizep2memfunclibEmJetAnalysis_Dict()
{
  G__Sizep2memfunclibEmJetAnalysis_Dict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancelibEmJetAnalysis_Dict() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetablelibEmJetAnalysis_Dict() {

   /* Setting up typedef entry */
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("Bool_t",103,-1,0,-1);
   G__setnewtype(-1,"Boolean (0=false, 1=true) (bool)",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__libEmJetAnalysis_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__libEmJetAnalysis_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__libEmJetAnalysis_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__libEmJetAnalysis_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__libEmJetAnalysis_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__libEmJetAnalysis_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__libEmJetAnalysis_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__libEmJetAnalysis_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__libEmJetAnalysis_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__libEmJetAnalysis_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* EjAna */
static void G__setup_memvarEjAna(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__libEmJetAnalysis_DictLN_EjAna));
   { EjAna *p; p=(EjAna*)0x1000; if (p) { }
   G__memvar_setup((void*)(&EjAna::kDefaultDet),117,0,0,G__get_linked_tagnum(&G__libEmJetAnalysis_DictLN_TString),-1,-2,1,"kDefaultDet=",0,(char*)NULL);
   G__memvar_setup((void*)(&EjAna::kFmsEtaMin),100,0,0,-1,G__defined_typename("Double_t"),-2,1,"kFmsEtaMin=",0,(char*)NULL);
   G__memvar_setup((void*)(&EjAna::kFmsEtaMax),100,0,0,-1,G__defined_typename("Double_t"),-2,1,"kFmsEtaMax=",0,(char*)NULL);
   G__memvar_setup((void*)(&EjAna::kEEmcEtaMin),100,0,0,-1,G__defined_typename("Double_t"),-2,1,"kEEmcEtaMin=",0,(char*)NULL);
   G__memvar_setup((void*)(&EjAna::kEEmcEtaMax),100,0,0,-1,G__defined_typename("Double_t"),-2,1,"kEEmcEtaMax=",0,(char*)NULL);
   G__memvar_setup((void*)(&EjAna::kPtMin),100,0,0,-1,G__defined_typename("Double_t"),-2,1,"kPtMin=",0,(char*)NULL);
   G__memvar_setup((void*)(&EjAna::kFmsEngMin),100,0,0,-1,G__defined_typename("Double_t"),-2,1,"kFmsEngMin=",0,"Fms Photon energy cut");
   G__memvar_setup((void*)(&EjAna::kEEmcEtMin),100,0,0,-1,G__defined_typename("Double_t"),-2,1,"kEEmcEtMin=",0,"EEmc tower energy_t cut");
   G__memvar_setup((void*)(&EjAna::kRMax),100,0,0,-1,G__defined_typename("Double_t"),-2,1,"kRMax=",0,"Anti kT radius");
   G__memvar_setup((void*)(&EjAna::kFMS_JP0),105,0,0,-1,G__defined_typename("Int_t"),-2,1,"kFMS_JP0=",0,(char*)NULL);
   G__memvar_setup((void*)(&EjAna::kFMS_JP1),105,0,0,-1,G__defined_typename("Int_t"),-2,1,"kFMS_JP1=",0,(char*)NULL);
   G__memvar_setup((void*)(&EjAna::kFMS_JP2),105,0,0,-1,G__defined_typename("Int_t"),-2,1,"kFMS_JP2=",0,(char*)NULL);
   G__memvar_setup((void*)(&EjAna::kFMS_SM_BS1),105,0,0,-1,G__defined_typename("Int_t"),-2,1,"kFMS_SM_BS1=",0,(char*)NULL);
   G__memvar_setup((void*)(&EjAna::kFMS_SM_BS2),105,0,0,-1,G__defined_typename("Int_t"),-2,1,"kFMS_SM_BS2=",0,(char*)NULL);
   G__memvar_setup((void*)(&EjAna::kFMS_SM_BS3),105,0,0,-1,G__defined_typename("Int_t"),-2,1,"kFMS_SM_BS3=",0,(char*)NULL);
   G__memvar_setup((void*)(&EjAna::kFMS_LG_BS1),105,0,0,-1,G__defined_typename("Int_t"),-2,1,"kFMS_LG_BS1=",0,(char*)NULL);
   G__memvar_setup((void*)(&EjAna::kFMS_LG_BS2),105,0,0,-1,G__defined_typename("Int_t"),-2,1,"kFMS_LG_BS2=",0,(char*)NULL);
   G__memvar_setup((void*)(&EjAna::kFMS_LG_BS3),105,0,0,-1,G__defined_typename("Int_t"),-2,1,"kFMS_LG_BS3=",0,(char*)NULL);
   G__memvar_setup((void*)(&EjAna::kEHTO),105,0,0,-1,G__defined_typename("Int_t"),-2,1,"kEHTO=",0,(char*)NULL);
   G__memvar_setup((void*)(&EjAna::kJP1),105,0,0,-1,G__defined_typename("Int_t"),-2,1,"kJP1=",0,(char*)NULL);
   G__memvar_setup((void*)(&EjAna::kJP2),105,0,0,-1,G__defined_typename("Int_t"),-2,1,"kJP2=",0,(char*)NULL);
   G__memvar_setup((void*)(&EjAna::kEHT0_EJP1_L2Egamma),105,0,0,-1,G__defined_typename("Int_t"),-2,1,"kEHT0_EJP1_L2Egamma=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__libEmJetAnalysis_DictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   G__memvar_setup((void*)0,108,0,0,-1,-1,-1,4,"G__virtualinfo=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarlibEmJetAnalysis_Dict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncEjAna(void) {
   /* EjAna */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__libEmJetAnalysis_DictLN_EjAna));
   G__memfunc_setup("EjAna",447,G__libEmJetAnalysis_Dict_184_0_1, 105, G__get_linked_tagnum(&G__libEmJetAnalysis_DictLN_EjAna), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Print",525,G__libEmJetAnalysis_Dict_184_0_2, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&EjAna::Print) ), 0);
   G__memfunc_setup("Class",502,G__libEmJetAnalysis_Dict_184_0_3, 85, G__get_linked_tagnum(&G__libEmJetAnalysis_DictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&EjAna::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__libEmJetAnalysis_Dict_184_0_4, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&EjAna::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__libEmJetAnalysis_Dict_184_0_5, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&EjAna::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__libEmJetAnalysis_Dict_184_0_6, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&EjAna::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,G__libEmJetAnalysis_Dict_184_0_7, 85, G__get_linked_tagnum(&G__libEmJetAnalysis_DictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,G__libEmJetAnalysis_Dict_184_0_8, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,G__libEmJetAnalysis_Dict_184_0_9, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__libEmJetAnalysis_Dict_184_0_10, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__libEmJetAnalysis_Dict_184_0_11, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&EjAna::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__libEmJetAnalysis_Dict_184_0_12, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&EjAna::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__libEmJetAnalysis_Dict_184_0_13, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&EjAna::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__libEmJetAnalysis_Dict_184_0_14, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&EjAna::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("EjAna", 447, G__libEmJetAnalysis_Dict_184_0_15, (int) ('i'), G__get_linked_tagnum(&G__libEmJetAnalysis_DictLN_EjAna), -1, 0, 1, 1, 1, 0, "u 'EjAna' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~EjAna", 573, G__libEmJetAnalysis_Dict_184_0_16, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__libEmJetAnalysis_Dict_184_0_17, (int) ('u'), G__get_linked_tagnum(&G__libEmJetAnalysis_DictLN_EjAna), -1, 1, 1, 1, 1, 0, "u 'EjAna' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfunclibEmJetAnalysis_Dict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globallibEmJetAnalysis_Dict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
   G__memfunc_setup("EjReadAnalysisTree", 1791, G__libEmJetAnalysis_Dict__0_2180, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL
, (void*) NULL, 0);
}

static void G__cpp_setup_func22() {
   G__memfunc_setup("EjCalculateBeamAsymmetry", 2429, G__libEmJetAnalysis_Dict__0_2287, 121, -1, -1, 0, 3, 1, 1, 0, 
"u 'TString' - 0 - inFileName u 'TString' - 0 - outName "
"u 'TString' - 0 '\"fms\"' det", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("EjSimpleAnalysisTreeQa", 2207, G__libEmJetAnalysis_Dict__0_2288, 121, -1, -1, 0, 2, 1, 1, 0, 
"u 'TString' - 0 - inFileName u 'TString' - 0 '\"EjSimpleAnalysisTreeQa.root\"' outName", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("EjRunEmJetTreeMakerEEmcSmd", 2487, G__libEmJetAnalysis_Dict__0_2289, 121, -1, -1, 0, 4, 1, 1, 0, 
"u 'TString' - 0 '\"./inFiles_fms.list\"' inFile u 'TString' - 0 '\"jets.root\"' outFile "
"u 'TString' - 0 '\"fms\"' det g - 'Bool_t' 0 'kFALSE' isMC", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("EjPlotAn", 765, G__libEmJetAnalysis_Dict__0_2290, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("EjCalculateANextended", 2077, G__libEmJetAnalysis_Dict__0_2291, 121, -1, -1, 0, 3, 1, 1, 0, 
"u 'TString' - 0 - inFileName u 'TString' - 0 - outName "
"u 'TString' - 0 '\"fms\"' det", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("EjRunEmJetTreeMaker", 1849, G__libEmJetAnalysis_Dict__0_2292, 121, -1, -1, 0, 4, 1, 1, 0, 
"u 'TString' - 0 '\"./inFiles_fms.list\"' inFile u 'TString' - 0 '\"jets.root\"' outFile "
"u 'TString' - 0 '\"fms\"' det g - 'Bool_t' 0 'kFALSE' isMC", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("EjCreateBinnedHist", 1771, G__libEmJetAnalysis_Dict__0_2293, 121, -1, -1, 0, 5, 1, 1, 0, 
"i - 'Int_t' 0 - fillNo u 'TString' - 0 - fileNamePrefix "
"u 'TString' - 0 - det i - 'Int_t' 0 '-1' firstRun "
"i - 'Int_t' 0 '-1' lastRun", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("EjMakeAnalysisTree", 1793, G__libEmJetAnalysis_Dict__0_2294, 121, -1, -1, 0, 5, 1, 1, 0, 
"u 'TString' - 0 - det i - 'Int_t' 0 - nentries "
"u 'TString' - 0 - jetfile u 'TString' - 0 - skimfile "
"u 'TString' - 0 - outfile", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("EjJetQaPlots", 1174, G__libEmJetAnalysis_Dict__0_2295, 121, -1, -1, 0, 4, 1, 1, 0, 
"i - 'Int_t' 0 - nentries u 'TString' - 0 - jetfile "
"u 'TString' - 0 - skimfile u 'TString' - 0 - outfile", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("EjCreateBinnedHistZn", 1971, G__libEmJetAnalysis_Dict__0_2296, 121, -1, -1, 0, 3, 1, 1, 0, 
"u 'TString' - 0 - fileNamePrefix u 'TString' - 0 - det "
"i - 'Int_t' 0 - minNphotons", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("EjCalculateAN", 1228, G__libEmJetAnalysis_Dict__0_2297, 121, -1, -1, 0, 3, 1, 1, 0, 
"u 'TString' - 0 - inFileName u 'TString' - 0 - outName "
"u 'TString' - 0 '\"fms\"' det", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("EjCalculateANdirectMethod", 2472, G__libEmJetAnalysis_Dict__0_2298, 121, -1, -1, 0, 3, 1, 1, 0, 
"u 'TString' - 0 - inFileName u 'TString' - 0 - outName "
"u 'TString' - 0 '\"fms\"' det", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("EjAnalysisTreeQa", 1589, G__libEmJetAnalysis_Dict__0_2299, 121, -1, -1, 0, 3, 1, 1, 0, 
"u 'TString' - 0 - inFileName u 'TString' - 0 '\"EjAnaTreeQa.root\"' outName "
"u 'TString' - 0 '\"fms\"' det", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("EjANprojection", 1403, G__libEmJetAnalysis_Dict__0_2300, 121, -1, -1, 0, 3, 1, 1, 0, 
"u 'TString' - 0 - inFileName u 'TString' - 0 - outName "
"u 'TString' - 0 '\"fms\"' det", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("EjCalculateFalseAN", 1719, G__libEmJetAnalysis_Dict__0_2301, 121, -1, -1, 0, 3, 1, 1, 0, 
"u 'TString' - 0 - inFileName u 'TString' - 0 - outName "
"u 'TString' - 0 '\"fms\"' det", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("EjCreateBinnedHistExtended", 2588, G__libEmJetAnalysis_Dict__0_2302, 121, -1, -1, 0, 6, 1, 1, 0, 
"i - 'Int_t' 0 - fillNo u 'TString' - 0 - fileNamePrefix "
"u 'TString' - 0 - det i - 'Int_t' 0 '-1' firstRun "
"i - 'Int_t' 0 '-1' lastRun i - 'Int_t' 0 '1' minNphotons", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("EjCreateSimpleBinnedHist", 2389, G__libEmJetAnalysis_Dict__0_2305, 121, -1, -1, 0, 2, 1, 1, 0, 
"i - 'Int_t' 0 - fillNo u 'TString' - 0 - fileNamePrefix", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("EjMakeSimpleAnalysisTree", 2411, G__libEmJetAnalysis_Dict__0_2306, 121, -1, -1, 0, 5, 1, 1, 0, 
"u 'TString' - 0 - det i - 'Int_t' 0 - nentries "
"u 'TString' - 0 - jetfile u 'TString' - 0 - skimfile "
"u 'TString' - 0 - outfile", (char*) NULL
, (void*) NULL, 0);

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funclibEmJetAnalysis_Dict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__libEmJetAnalysis_DictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__libEmJetAnalysis_DictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__libEmJetAnalysis_DictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__libEmJetAnalysis_DictLN_TString = { "TString" , 99 , -1 };
G__linked_taginfo G__libEmJetAnalysis_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__libEmJetAnalysis_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__libEmJetAnalysis_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__libEmJetAnalysis_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__libEmJetAnalysis_DictLN_EjAna = { "EjAna" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtablelibEmJetAnalysis_Dict() {
  G__libEmJetAnalysis_DictLN_TClass.tagnum = -1 ;
  G__libEmJetAnalysis_DictLN_TBuffer.tagnum = -1 ;
  G__libEmJetAnalysis_DictLN_TMemberInspector.tagnum = -1 ;
  G__libEmJetAnalysis_DictLN_TString.tagnum = -1 ;
  G__libEmJetAnalysis_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__libEmJetAnalysis_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__libEmJetAnalysis_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__libEmJetAnalysis_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__libEmJetAnalysis_DictLN_EjAna.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtablelibEmJetAnalysis_Dict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__libEmJetAnalysis_DictLN_TClass);
   G__get_linked_tagnum_fwd(&G__libEmJetAnalysis_DictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__libEmJetAnalysis_DictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__libEmJetAnalysis_DictLN_TString);
   G__get_linked_tagnum_fwd(&G__libEmJetAnalysis_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__libEmJetAnalysis_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__libEmJetAnalysis_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__libEmJetAnalysis_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__libEmJetAnalysis_DictLN_EjAna),sizeof(EjAna),-1,1280,(char*)NULL,G__setup_memvarEjAna,G__setup_memfuncEjAna);
}
extern "C" void G__cpp_setuplibEmJetAnalysis_Dict(void) {
  G__check_setup_version(30051515,"G__cpp_setuplibEmJetAnalysis_Dict()");
  G__set_cpp_environmentlibEmJetAnalysis_Dict();
  G__cpp_setup_tagtablelibEmJetAnalysis_Dict();

  G__cpp_setup_inheritancelibEmJetAnalysis_Dict();

  G__cpp_setup_typetablelibEmJetAnalysis_Dict();

  G__cpp_setup_memvarlibEmJetAnalysis_Dict();

  G__cpp_setup_memfunclibEmJetAnalysis_Dict();
  G__cpp_setup_globallibEmJetAnalysis_Dict();
  G__cpp_setup_funclibEmJetAnalysis_Dict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfunclibEmJetAnalysis_Dict();
  return;
}
class G__cpp_setup_initlibEmJetAnalysis_Dict {
  public:
    G__cpp_setup_initlibEmJetAnalysis_Dict() { G__add_setup_func("libEmJetAnalysis_Dict",(G__incsetup)(&G__cpp_setuplibEmJetAnalysis_Dict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initlibEmJetAnalysis_Dict() { G__remove_setup_func("libEmJetAnalysis_Dict"); }
};
G__cpp_setup_initlibEmJetAnalysis_Dict G__cpp_setup_initializerlibEmJetAnalysis_Dict;

